# Generated by Django 4.2.14 on 2024-10-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_register_final_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='semester',
            field=models.TextField(choices=[(1, 'Học kỳ 1'), (2, 'Học kỳ 2'), (3, 'Học kỳ 3')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='study_section',
            name='is_open',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
