# Generated by Django 4.2.14 on 2024-10-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_register_semester_study_section_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='semester',
            field=models.TextField(choices=[('1', 'Học kỳ 1'), ('2', 'Học kỳ 2'), ('3', 'Học kỳ 3')], default=1, max_length=1),
        ),
    ]
