# Generated by Django 3.2.4 on 2024-10-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='images\x07vatar-trang-4.jpg', upload_to=''),
        ),
    ]
