# Generated by Django 4.2.14 on 2024-10-19 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_register_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='study_section',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='study_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.study_section'),
        ),
    ]
