# Generated by Django 3.2.4 on 2024-10-07 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='status',
        ),
    ]
