# Generated by Django 4.2.14 on 2024-10-19 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_lecturer_study_section_lecturer_study_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.register'),
        ),
    ]
