# Generated by Django 3.2.4 on 2024-10-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20241007_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='123', max_length=128),
        ),
    ]
